"""Add message field to alerts table

Revision ID: 8c2ff02adad7
Revises: 
Create Date: 2025-10-18 01:14:33.958189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2ff02adad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cotizacion', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cotizacion'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_cotizacion_id'), 'items_cotizacion', ['id'], unique=False)
    op.drop_index('ix_documents_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_credit_approvals_id', table_name='credit_approvals')
    op.drop_table('credit_approvals')
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_deliveries_id', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index('ix_payment_schedules_id', table_name='payment_schedules')
    op.drop_table('payment_schedules')
    op.drop_index('ix_document_types_id', table_name='document_types')
    op.drop_table('document_types')
    op.drop_index('ix_event_log_id', table_name='event_log')
    op.drop_table('event_log')
    op.drop_index('ix_delivery_photos_id', table_name='delivery_photos')
    op.drop_table('delivery_photos')
    op.drop_index('ix_guarantees_id', table_name='guarantees')
    op.drop_table('guarantees')
    op.drop_index('ix_vehicles_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_vehicle_assignments_id', table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    op.drop_index('ix_credit_applications_id', table_name='credit_applications')
    op.drop_table('credit_applications')
    op.add_column('alertas', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alertas', 'message')
    op.create_table('credit_applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cotizacion', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('requested_amount', sa.FLOAT(), nullable=True),
    sa.Column('approved_amount', sa.FLOAT(), nullable=True),
    sa.Column('term_months', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cotizacion'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_applications_id', 'credit_applications', ['id'], unique=False)
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cotizacion', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('assigned_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('released_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cotizacion'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_assignments_id', 'vehicle_assignments', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vin', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('available', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index('ix_vehicles_id', 'vehicles', ['id'], unique=False)
    op.create_table('guarantees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['credit_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guarantees_id', 'guarantees', ['id'], unique=False)
    op.create_table('delivery_photos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('delivery_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_photos_id', 'delivery_photos', ['id'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=50), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_log_id', 'event_log', ['id'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('required_in_stage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_document_types_id', 'document_types', ['id'], unique=False)
    op.create_table('payment_schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cotizacion', sa.INTEGER(), nullable=False),
    sa.Column('installment_number', sa.INTEGER(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('amount_due', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cotizacion'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_schedules_id', 'payment_schedules', ['id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cotizacion', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('delivered_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cotizacion'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_id', 'deliveries', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), nullable=False),
    sa.Column('paid_amount', sa.FLOAT(), nullable=False),
    sa.Column('paid_date', sa.DATE(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=30), nullable=True),
    sa.Column('receipt_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['payment_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.create_table('credit_approvals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('approved_amount', sa.FLOAT(), nullable=False),
    sa.Column('term_months', sa.INTEGER(), nullable=False),
    sa.Column('letter_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['credit_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_approvals_id', 'credit_approvals', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cotizacion', sa.INTEGER(), nullable=False),
    sa.Column('document_type_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=500), nullable=False),
    sa.Column('mimetype', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('note', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cotizacion'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_id', 'documents', ['id'], unique=False)
    op.drop_index(op.f('ix_items_cotizacion_id'), table_name='items_cotizacion')
    op.drop_table('items_cotizacion')
    # ### end Alembic commands ###
